USE master
go
ALTER DATABASE ArchiveDB			SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
ALTER DATABASE CustomerDB		SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
ALTER DATABASE OrdersDB		SET SINGLE_USER WITH ROLLBACK IMMEDIATE;


go
DROP DATABASE ArchiveDB			
DROP DATABASE CustomerDB		
DROP DATABASE OrdersDB	


GO

CREATE DATABASE ArchiveDB		
CREATE DATABASE CustomerDB		
CREATE DATABASE OrdersDB	
GO

ALTER DATABASE ArchiveDB	sET TRUSTWORTHY ON;
ALTER DATABASE CustomerDB	sET TRUSTWORTHY ON;
ALTER DATABASE OrdersDB		SET TRUSTWORTHY ON;